stages:
  - test
  - build

test:
  stage: test
  image: painless/tox
  script:
    - which docker
    - docker run -it -v $(pwd):/tmp/app -w /tmp/app --rm painless/tox /bin/bash tox

# build:
#   stage: build
#   image: tmaier/docker-compose:latest
#   tags:
#     - gitlab-org-docker
#   script:
#     - docker-compose build