stages:
  - test
  - build

test:
  stage: test
  image: docker:latest
  tags:
    - gitlab-org-docker
  script:
    - docker run busybox:latest echo hello
    - echo end-of-script

build:
  stage: build
  image: tmaier/docker-compose:latest
  script:
    - docker-compose build