stages:
  - test
  - build

variables:
  CI_REGISTRY_USER: 'registry.gitlab.com'
  FLASK_IMAGE: 'registry.gitlab.com/jose.bustos/the-real-devops-challenge/flaskapp'
  MONGODB_IMAGE: 'registry.gitlab.com/jose.bustos/the-real-devops-challenge/mongodb'

test:
  stage: test
  image: painless/tox
  script:
    - tox

build-flask:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $FLASK_IMAGE .
    - docker push $FLASK_IMAGE

build-mongo:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.12-dind
  script:
    - docker login $CI_REGISTRY
    - docker build -t $MONGODB_IMAGE .
    - docker push $MONGODB_IMAGE