image: docker:latest

test:
  tags:
    - gitlab-org-docker
  script:
    - docker run -it -v $(pwd):/tmp/app -w /tmp/app --rm painless/tox /bin/bash tox

# build:
#   tags:
#     - gitlab-org-docker
#   script:
#    - docker-compose up -d