image: customregistry/docker-builder:latest

stages:
  - test
  - build

test:
  stage: test
  image: docker:latest
  tags:
    - docker-in-docker-builder 
  script:
    - echo start-of-script
    - docker run busybox:latest echo hello
    - echo end-of-script

build:
  stage: build
  image: tmaier/docker-compose:latest
  script:
    - docker-compose build