stages:
  - test
  - build

test:
  stage: test
  image: python:3.6.8-alpine3.9
  tags:
    - gitlab-org-docker
  script:
    - echo start-of-script
    - pip install tox
    - tox

# build:
#   stage: build
#   image: tmaier/docker-compose:latest
#   tags:
#     - gitlab-org-docker
#   script:
#     - docker-compose build