stages:
  - test
  - build

variables:
  CI_REGISTRY_USER: 'registry.gitlab.com'
  FLASK_IMAGE: 'devops-challenge-flask:latest'
  MONGODB_IMAGE: 'devops-challenge-mongo:latest'

test:
  stage: test
  image: painless/tox
  script:
    - tox

build-flask:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.12-dind
  script:
    - docker login $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$FLASK_IMAGE .
    - docker push $CI_REGISTRY/$FLASK_IMAGE

build-mongo:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.12-dind
  script:
    - docker login $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$MONGODB_IMAGE .
    - docker push $CI_REGISTRY/$MONGODB_IMAGE