apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: jotabustosigz/devops-challenge-flask:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_DATABASE
              value: "flaskdb"
            - name: MONGODB_USERNAME
              value: "flaskuser"
            - name: MONGODB_PASSWORD
              value: "your_mongodb_password"
            - name: MONGODB_HOSTNAME
              value: "mongodb"
          imagePullPolicy: Always