apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: devops-challenge
spec:
  containers:
    - name: mongodb
      image: jotabustosigz/devops-challenge-mongodb:3.0
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "mongodbuser"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "your_mongodb_root_password"
        - name: MONGO_INITDB_DATABASE
          value: "flaskdb"
        - name: MONGODB_DATA_DIR
          value: "/data/db"
        - name: MONDODB_LOG_DIR
          value: "/dev/null"
      terminationMessagePath: "/tmp/my-log"