apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels: 
    name: mongo-service
    app: devops-challenge
spec:
  selector:
    app: devops-challenge
    name: mongodb
  ports:
    - port: 27017
      targetPort: 27017